<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ClientServer.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <InternalsVisibleTo Include="Client-Server-App" />
    <InternalsVisibleTo Include="Client-Server-App.Tests" />
    <InternalsVisibleTo Include="Client-Server-App.UiTests" />
  </ItemGroup>

</Project>
