<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>ClientServer.App</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <InternalsVisibleTo Include="Client-Server-App.UiTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Client-Server-App.Core\Client-Server-App.Core.csproj" />
  </ItemGroup>

</Project>
