<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <UseWPF>true</UseWPF>
    <RootNamespace>ClientServer.UiTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Xunit.StaFact" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Client-Server-App.Core\Client-Server-App.Core.csproj" />
    <ProjectReference Include="..\..\src\Client-Server-App\Client-Server-App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\TestSupport\**\*.cs" LinkBase="TestSupport" />
  </ItemGroup>

</Project>
